ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[[rule]]
name = "missing-method-doc"
severity = "error"
message = "Method is missing a documentation comment."

[rule.missing-method-doc]
match = '''
^\s*func\s+\w+\s*\(.*\)\s*\{$
'''

[rule.missing-method-doc.exclude]
expression = '''
^\s*func\s+\w+\s*\(.*\)\s*\{$
'''

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.line-length-limit]
    severity = "error"
    arguments = [180]
[rule.var-naming]
    arguments = [["ID","URL","IP","HTTP","JSON","API","UID","Id","Api","Uid","Http","Json","Ip","Url"], ["VM"]]
[rule.var-declaration]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.waitgroup-by-value]
    severity = "warning"
    disable = false
