// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package home

import (
	"github.com/houseme/url-shortenter/app/front/api/home"
)

type ControllerV1 struct{}

func NewV1() home.IHomeV1 {
	return &ControllerV1{}
}
