// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package statistic

import (
	"github.com/houseme/url-shortenter/app/console/api/statistic"
)

// ControllerV1 is the controller for statistic.
type ControllerV1 struct{}

// NewV1 is used to create a new statistic controller.
func NewV1() statistic.IStatisticV1 {
	return &ControllerV1{}
}
