// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package access

import (
	"github.com/houseme/url-shortenter/app/console/api/access"
)

// ControllerV1 is the implement of the interface IAccessV1 Controller.
type ControllerV1 struct{}

// NewV1 creates and returns a new access ControllerV1 object.
func NewV1() access.IAccessV1 {
	return &ControllerV1{}
}
