// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/houseme/url-shortenter/app/console/internal/logic/home"
	_ "github.com/houseme/url-shortenter/app/console/internal/logic/user"
)
