// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

// Package hello is a demo controller for output "Hello World!". It's used for test purpose.
package hello
