// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package hello

import (
	"github.com/houseme/url-shortenter/app/front/api/hello"
)

// ControllerV1 is a demo controller for output "Hello World!". It's used for test purpose.
type ControllerV1 struct{}

// NewV1 creates and returns a new hello controller object.
func NewV1() hello.IHelloV1 {
	return &ControllerV1{}
}
