// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalAccessLogsSummaryDao is internal type for wrapping internal DAO implements.
type internalAccessLogsSummaryDao = *internal.AccessLogsSummaryDao

// accessLogsSummaryDao is the data access object for table access_logs_summary.
// You can define custom methods on it to extend its functionality as you wish.
type accessLogsSummaryDao struct {
	internalAccessLogsSummaryDao
}

var (
	// AccessLogsSummary is globally public accessible object for table access_logs_summary operations.
	AccessLogsSummary = accessLogsSummaryDao{
		internal.NewAccessLogsSummaryDao(),
	}
)

// Fill with you ideas below.
