// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalShortTagRelationDao is internal type for wrapping internal DAO implements.
type internalShortTagRelationDao = *internal.ShortTagRelationDao

// shortTagRelationDao is the data access object for table short_tag_relation.
// You can define custom methods on it to extend its functionality as you wish.
type shortTagRelationDao struct {
	internalShortTagRelationDao
}

var (
	// ShortTagRelation is globally public accessible object for table short_tag_relation operations.
	ShortTagRelation = shortTagRelationDao{
		internal.NewShortTagRelationDao(),
	}
)

// Fill with you ideas below.
