// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalShortContentRecordDao is internal type for wrapping internal DAO implements.
type internalShortContentRecordDao = *internal.ShortContentRecordDao

// shortContentRecordDao is the data access object for table short_content_record.
// You can define custom methods on it to extend its functionality as you wish.
type shortContentRecordDao struct {
	internalShortContentRecordDao
}

var (
	// ShortContentRecord is globally public accessible object for table short_content_record operations.
	ShortContentRecord = shortContentRecordDao{
		internal.NewShortContentRecordDao(),
	}
)

// Fill with you ideas below.
