// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalShortRawDao is internal type for wrapping internal DAO implements.
type internalShortRawDao = *internal.ShortRawDao

// shortRawDao is the data access object for table short_raw.
// You can define custom methods on it to extend its functionality as you wish.
type shortRawDao struct {
	internalShortRawDao
}

var (
	// ShortRaw is globally public accessible object for table short_raw operations.
	ShortRaw = shortRawDao{
		internal.NewShortRawDao(),
	}
)

// Fill with you ideas below.
