// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalShortMirrorDao is internal type for wrapping internal DAO implements.
type internalShortMirrorDao = *internal.ShortMirrorDao

// shortMirrorDao is the data access object for table short_mirror.
// You can define custom methods on it to extend its functionality as you wish.
type shortMirrorDao struct {
	internalShortMirrorDao
}

var (
	// ShortMirror is globally public accessible object for table short_mirror operations.
	ShortMirror = shortMirrorDao{
		internal.NewShortMirrorDao(),
	}
)

// Fill with you ideas below.
