// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalShortAuditLogDao is internal type for wrapping internal DAO implements.
type internalShortAuditLogDao = *internal.ShortAuditLogDao

// shortAuditLogDao is the data access object for table short_audit_log.
// You can define custom methods on it to extend its functionality as you wish.
type shortAuditLogDao struct {
	internalShortAuditLogDao
}

var (
	// ShortAuditLog is globally public accessible object for table short_audit_log operations.
	ShortAuditLog = shortAuditLogDao{
		internal.NewShortAuditLogDao(),
	}
)

// Fill with you ideas below.
