// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalShortDomainDao is internal type for wrapping internal DAO implements.
type internalShortDomainDao = *internal.ShortDomainDao

// shortDomainDao is the data access object for table short_domain.
// You can define custom methods on it to extend its functionality as you wish.
type shortDomainDao struct {
	internalShortDomainDao
}

var (
	// ShortDomain is globally public accessible object for table short_domain operations.
	ShortDomain = shortDomainDao{
		internal.NewShortDomainDao(),
	}
)

// Fill with you ideas below.
