// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalSumUrlIpCountStatsDao is internal type for wrapping internal DAO implements.
type internalSumUrlIpCountStatsDao = *internal.SumUrlIpCountStatsDao

// sumUrlIpCountStatsDao is the data access object for table sum_url_ip_count_stats.
// You can define custom methods on it to extend its functionality as you wish.
type sumUrlIpCountStatsDao struct {
	internalSumUrlIpCountStatsDao
}

var (
	// SumUrlIpCountStats is globally public accessible object for table sum_url_ip_count_stats operations.
	SumUrlIpCountStats = sumUrlIpCountStatsDao{
		internal.NewSumUrlIpCountStatsDao(),
	}
)

// Fill with you ideas below.
