// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalTotalCountTop25Dao is internal type for wrapping internal DAO implements.
type internalTotalCountTop25Dao = *internal.TotalCountTop25Dao

// totalCountTop25Dao is the data access object for table total_count_top25.
// You can define custom methods on it to extend its functionality as you wish.
type totalCountTop25Dao struct {
	internalTotalCountTop25Dao
}

var (
	// TotalCountTop25 is globally public accessible object for table total_count_top25 operations.
	TotalCountTop25 = totalCountTop25Dao{
		internal.NewTotalCountTop25Dao(),
	}
)

// Fill with you ideas below.
