// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalUrlIpCountStatsDao is internal type for wrapping internal DAO implements.
type internalUrlIpCountStatsDao = *internal.UrlIpCountStatsDao

// urlIpCountStatsDao is the data access object for table url_ip_count_stats.
// You can define custom methods on it to extend its functionality as you wish.
type urlIpCountStatsDao struct {
	internalUrlIpCountStatsDao
}

var (
	// UrlIpCountStats is globally public accessible object for table url_ip_count_stats operations.
	UrlIpCountStats = urlIpCountStatsDao{
		internal.NewUrlIpCountStatsDao(),
	}
)

// Fill with you ideas below.
