// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalUserTagRelationDao is internal type for wrapping internal DAO implements.
type internalUserTagRelationDao = *internal.UserTagRelationDao

// userTagRelationDao is the data access object for table user_tag_relation.
// You can define custom methods on it to extend its functionality as you wish.
type userTagRelationDao struct {
	internalUserTagRelationDao
}

var (
	// UserTagRelation is globally public accessible object for table user_tag_relation operations.
	UserTagRelation = userTagRelationDao{
		internal.NewUserTagRelationDao(),
	}
)

// Fill with you ideas below.
