// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalUsersDomainAuditDao is internal type for wrapping internal DAO implements.
type internalUsersDomainAuditDao = *internal.UsersDomainAuditDao

// usersDomainAuditDao is the data access object for table users_domain_audit.
// You can define custom methods on it to extend its functionality as you wish.
type usersDomainAuditDao struct {
	internalUsersDomainAuditDao
}

var (
	// UsersDomainAudit is globally public accessible object for table users_domain_audit operations.
	UsersDomainAudit = usersDomainAuditDao{
		internal.NewUsersDomainAuditDao(),
	}
)

// Fill with you ideas below.
