// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalUserMerchantDao is internal type for wrapping internal DAO implements.
type internalUserMerchantDao = *internal.UserMerchantDao

// userMerchantDao is the data access object for table user_merchant.
// You can define custom methods on it to extend its functionality as you wish.
type userMerchantDao struct {
	internalUserMerchantDao
}

var (
	// UserMerchant is globally public accessible object for table user_merchant operations.
	UserMerchant = userMerchantDao{
		internal.NewUserMerchantDao(),
	}
)

// Fill with you ideas below.
