// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalUsersAccessSecretDao is internal type for wrapping internal DAO implements.
type internalUsersAccessSecretDao = *internal.UsersAccessSecretDao

// usersAccessSecretDao is the data access object for table users_access_secret.
// You can define custom methods on it to extend its functionality as you wish.
type usersAccessSecretDao struct {
	internalUsersAccessSecretDao
}

var (
	// UsersAccessSecret is globally public accessible object for table users_access_secret operations.
	UsersAccessSecret = usersAccessSecretDao{
		internal.NewUsersAccessSecretDao(),
	}
)

// Fill with you ideas below.
