// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalUserAccessSecretDao is internal type for wrapping internal DAO implements.
type internalUserAccessSecretDao = *internal.UserAccessSecretDao

// userAccessSecretDao is the data access object for table user_access_secret.
// You can define custom methods on it to extend its functionality as you wish.
type userAccessSecretDao struct {
	internalUserAccessSecretDao
}

var (
	// UserAccessSecret is globally public accessible object for table user_access_secret operations.
	UserAccessSecret = userAccessSecretDao{
		internal.NewUserAccessSecretDao(),
	}
)

// Fill with you ideas below.
