// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalUsersDomainDao is internal type for wrapping internal DAO implements.
type internalUsersDomainDao = *internal.UsersDomainDao

// usersDomainDao is the data access object for table users_domain.
// You can define custom methods on it to extend its functionality as you wish.
type usersDomainDao struct {
	internalUsersDomainDao
}

var (
	// UsersDomain is globally public accessible object for table users_domain operations.
	UsersDomain = usersDomainDao{
		internal.NewUsersDomainDao(),
	}
)

// Fill with you ideas below.
