// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalUserDomainDao is internal type for wrapping internal DAO implements.
type internalUserDomainDao = *internal.UserDomainDao

// userDomainDao is the data access object for table user_domain.
// You can define custom methods on it to extend its functionality as you wish.
type userDomainDao struct {
	internalUserDomainDao
}

var (
	// UserDomain is globally public accessible object for table user_domain operations.
	UserDomain = userDomainDao{
		internal.NewUserDomainDao(),
	}
)

// Fill with you ideas below.
