// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/houseme/url-shortenter/internal/database/dao/internal"
)

// internalUserDomainAuditDao is internal type for wrapping internal DAO implements.
type internalUserDomainAuditDao = *internal.UserDomainAuditDao

// userDomainAuditDao is the data access object for table user_domain_audit.
// You can define custom methods on it to extend its functionality as you wish.
type userDomainAuditDao struct {
	internalUserDomainAuditDao
}

var (
	// UserDomainAudit is globally public accessible object for table user_domain_audit operations.
	UserDomainAudit = userDomainAuditDao{
		internal.NewUserDomainAuditDao(),
	}
)

// Fill with you ideas below.
