// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UsersAccessSecret is the golang structure of table users_access_secret for DAO operations like Where/Data.
type UsersAccessSecret struct {
	g.Meta     `orm:"table:users_access_secret, do:true"`
	Id         interface{} // ID
	AccountNo  interface{} // 企业管理员ID一致
	SecretId   interface{} // 授权应用ID
	SecretKey  interface{} // 授权应用key
	Salt       interface{} // 盐值
	SaltKey    interface{} // 盐值key
	GrantType  interface{} // 授权类型： 默认空，API token授权:client_credentials
	State      interface{} // 状态 0默认 100正常 200禁用
	CreateTime *gtime.Time // 创建时间
	ModifyTime *gtime.Time // 修改时间
}
