// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/houseme/url-shortenter/app/schedule/internal/logic/lark"
	_ "github.com/houseme/url-shortenter/app/schedule/internal/logic/short"
)
