// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/houseme/url-shortenter/app/console/internal/model"
)

type (
	IAccess interface {
		List(ctx context.Context, in *model.AccessListInput) (out *model.AccessListOutput, err error)
		Detail(ctx context.Context, in *model.AccessDetailInput) (out *model.AccessDetailOutput, err error)
	}
)

var (
	localAccess IAccess
)

func Access() IAccess {
	if localAccess == nil {
		panic("implement not found for interface IAccess, forgot register?")
	}
	return localAccess
}

func RegisterAccess(i IAccess) {
	localAccess = i
}
