// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/houseme/url-shortenter/app/console/internal/model"
)

type IAccount interface {
	CreateAccount(ctx context.Context, in *model.CreateAccountInput) (out *model.CreateAccountOutput, err error)
	ModifyAccount(ctx context.Context, in *model.ModifyAccountInput) (out *model.ModifyAccountOutput, err error)
	ModifyPassword(ctx context.Context, in *model.ModifyPasswordInput) (out *model.ModifyPasswordOutput, err error)
}

var localAccount IAccount

func Account() IAccount {
	if localAccount == nil {
		panic("implement not found for interface IAccount, forgot register?")
	}
	return localAccount
}

func RegisterAccount(i IAccount) {
	localAccount = i
}
