// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/houseme/url-shortenter/app/console/internal/model"
)

type IAuth interface {
	CreateAccessToken(ctx context.Context, in *model.CreateAccessTokenInput) (out *model.CreateAccessTokenOutput, err error)
	Authorization(ctx context.Context, in *model.AuthInput) (out *model.AuthOutput, err error)
}

var localAuth IAuth

func Auth() IAuth {
	if localAuth == nil {
		panic("implement not found for interface IAuth, forgot register?")
	}
	return localAuth
}

func RegisterAuth(i IAuth) {
	localAuth = i
}
