// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/houseme/url-shortenter/app/console/internal/model"
)

type IHome interface {
	Index(ctx context.Context, in *model.HomeIndexInput) (out *model.HomeIndexOutput, err error)
}

var localHome IHome

func Home() IHome {
	if localHome == nil {
		panic("implement not found for interface IHome, forgot register?")
	}
	return localHome
}

func RegisterHome(i IHome) {
	localHome = i
}
