// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/houseme/url-shortenter/app/console/internal/model"
)

type IShort interface {
	CreateShort(ctx context.Context, in *model.CreateShortInput) (out *model.CreateShortOutput, err error)
	ModifyShort(ctx context.Context, in *model.ModifyShortInput) (out *model.ModifyShortOutput, err error)
	QueryShort(ctx context.Context, in *model.QueryShortInput) (out *model.QueryShortOutput, err error)
	QueryStat(ctx context.Context, in *model.QueryStatInput) (out *model.QueryStatOutput, err error)
}

var localShort IShort

func Short() IShort {
	if localShort == nil {
		panic("implement not found for interface IShort, forgot register?")
	}
	return localShort
}

func RegisterShort(i IShort) {
	localShort = i
}
