// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/houseme/url-shortenter/app/console/internal/model"
)

type (
	IStatistic interface {
		List(ctx context.Context, in *model.StatisticListInput) (out *model.StatisticListOutput, err error)
		Detail(ctx context.Context, in *model.StatisticDetailInput) (out *model.StatisticDetailOutput, err error)
	}
)

var (
	localStatistic IStatistic
)

func Statistic() IStatistic {
	if localStatistic == nil {
		panic("implement not found for interface IStatistic, forgot register?")
	}
	return localStatistic
}

func RegisterStatistic(i IStatistic) {
	localStatistic = i
}
