// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	"github.com/houseme/url-shortenter/app/console/api/auth"
)

// ControllerV1 is the implement of the interface IAuthV1 Controller.
type ControllerV1 struct{}

// NewV1 creates and returns a new auth ControllerV1 object.
func NewV1() auth.IAuthV1 {
	return &ControllerV1{}
}
