// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SumUrlIpCountStats is the golang structure for table sum_url_ip_count_stats.
type SumUrlIpCountStats struct {
	TodayCount  int64 `json:"todayCount"  description:""`
	DTodayCount int64 `json:"dTodayCount" description:""`
}
