// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package short

import (
	"github.com/houseme/url-shortenter/app/console/api/short"
)

// ControllerV1 is for account controller implementation.
type ControllerV1 struct{}

// NewV1 creates and returns a new account controller object.
func NewV1() short.IShortV1 {
	return &ControllerV1{}
}
