// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package echo

import (
	"github.com/houseme/url-shortenter/app/console/api/echo"
)

// ControllerV1 is the implement of the interface IEchoV1 Controller.
type ControllerV1 struct{}

// NewV1 creates and returns a new echo ControllerV1 object.
func NewV1() echo.IEchoV1 {
	return &ControllerV1{}
}
