# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # 工具编译配置
  build:
    name: "url-shortenter-front"
    arch: "amd64"
    system: "linux"
    mod: ""
    cgo: 0
    path: "./manifest/output"
    pack: "manifest/config,resource/public"
    output: ""
    version: "v1.0.0"
  # dao 生成
  gen:
    dao:
      - link: "mysql:root:root@tcp(127.0.0.1:3306)/oh_url_shortener?charset=utf8mb4&parseTime=True&loc=Local"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
        tables: ""
        group: "default"
        overwriteDao: true
        path: "internal/database"
