// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"github.com/houseme/url-shortenter/app/console/api/user"
)

// ControllerV1 is the controller for version 1 of the user API
type ControllerV1 struct{}

// NewV1 creates a new instance of the user controller
func NewV1() user.IUserV1 {
	return &ControllerV1{}
}
