// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package account

import (
	"github.com/houseme/url-shortenter/app/console/api/account"
)

// ControllerV1 is the implement of the interface IAccountV1 Controller.
type ControllerV1 struct{}

// NewV1 creates and returns a new account ControllerV1 object.
func NewV1() account.IAccountV1 {
	return &ControllerV1{}
}
