// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/houseme/url-shortenter/app/schedule/internal/model"
)

type ILark interface {
	SendMessage(ctx context.Context, in *model.SendMessageInput) (out *model.SendMessageOutput, err error)
}

var localLark ILark

func Lark() ILark {
	if localLark == nil {
		panic("implement not found for interface ILark, forgot register?")
	}
	return localLark
}

func RegisterLark(i ILark) {
	localLark = i
}
