// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"

	"github.com/houseme/url-shortenter/internal/database/model/entity"
)

type IShort interface {
	AssignTask(ctx context.Context) error
	AuditAssignTask(ctx context.Context) error
	ExecuteAudit(ctx context.Context)
	QueryShortAndGrabAudit(ctx context.Context)
	GrabImageAudit(ctx context.Context, shortURL *entity.ShortUrls) error
	ReportHashChange(ctx context.Context, shortAudit *entity.ShortAuditLog, basePath string) error
	AccessLog(ctx context.Context) error
	ShortAccessLogSummary(ctx context.Context) error
	GetShortCache(ctx context.Context, short string) (*entity.ShortUrls, error)
	GrabImage(ctx context.Context, shortURL *entity.ShortUrls) error
	Execute(ctx context.Context)
	RequestContent(ctx context.Context, url, fileName string) ([]byte, error)
	RequestStatusCode(ctx context.Context, url string) (int, error)
	DownloadFullScreenshot(ctx context.Context, url, fileName string) (err error)
}

var localShort IShort

func Short() IShort {
	if localShort == nil {
		panic("implement not found for interface IShort, forgot register?")
	}
	return localShort
}

func RegisterShort(i IShort) {
	localShort = i
}
