// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package domain

import (
	"github.com/houseme/url-shortenter/app/console/api/domain"
)

type ControllerV1 struct{}

func NewV1() domain.IDomainV1 {
	return &ControllerV1{}
}
