// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package domain

import (
	"github.com/houseme/url-shortenter/app/console/api/domain"
)

// ControllerV1 is the implement of the interface IDomainV1 Controller.
type ControllerV1 struct{}

// NewV1 creates and returns a new ControllerV1 object.
func NewV1() domain.IDomainV1 {
	return &ControllerV1{}
}
