// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/houseme/url-shortenter/app/front/internal/logic/home"
	_ "github.com/houseme/url-shortenter/app/front/internal/logic/middleware"
)
