name: Url-Shortenter CI

on:
  push:
    branches:
      - main
      - fix/**
      - feature/**
      - develop
  pull_request:
    branches:
      - main
      - fix/**
      - feature/**
      - develop

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [ "1.21","1.22" ]
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.56.2
          args: --timeout 3m0s

  Reviveci:
    strategy:
      matrix:
        go-version: [ "1.21","1.22" ]
    name: Run Revive Action
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - name: Run Revive Action
        uses: morphy2k/revive-action@v2
        with:
          # Path to your Revive config within the repo (optional)
          config: revive.toml

  AutoCorrect:
    runs-on: ubuntu-latest
    # strategy set
    strategy:
      matrix:
        go: [ "1.21","1.22" ]
    steps:
      - name: Check source code
        uses: actions/checkout@v4

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@main
  #        with:
  #          args: --lint --no-diff-bg-color $(git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }}}

  build:
    runs-on: ubuntu-latest
    # strategy set
    strategy:
      matrix:
        go: [ "1.21","1.22" ]
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
